### ISSUE TITLE
/etc/init.d/mongod conflicts with /etc/init.d/mongos on server reboot

### ISSUE THREAD

**Issue by utf8please** [aws-quickstart/quickstart-mongodb#1]
I used this script some time ago to deploy a mongo cluster. The parameters were 2 shards, each replicated.

Everything had been working fine, until three days ago `PrimaryReplicaNode10` rebooted for some reason beyond my knowledge. And that node started running `mongod` on 27017 instead of `mongos`.

This caused some trouble in the application layer, because the application did not notice the difference between `mongod` and `mongos` and all the data appears to be deleted because the `mongod` is empty and does not have the query routing functionality.

Trying to locate the problem, I ssh-ed into `PrimaryReplicaNode10` and found the script has created three service files for me: `/etc/init.d/mongod`, `/etc/init.d/mongod0`, `/etc/init.d/mongos`. From my understanding of the script, the `mongod0` is there because the code block with the `When there is sharding, make sure atleast one microshard` comment. And it is running on 27018 (a different port), which seems to be correct. And `mongos` is configured to be running on 27017, which is also expected.

Now what confuses me is the `/etc/init.d/mongod` service. It is also configured to run on 27017, so it will prevent `mongos` from starting. In other words, the final running instances would be either be `mongos (27017)` + `mongod0 (27018)` (expected), or `mongod (27017)` and `mongod0 (27018)` which does not make sense to me.

I manually removed the `/etc/init/mongod` service and all is good now. Why is that file not removed in the first place? I don't see a reason of having a separate mongod and its configuration files dangling there if micro-sharding is enabled.

Also, the `mongod` service wasn't started during initial setup because it was in the else branch of `if [ "${MICROSHARDS}" != "0" ]; then`. So the problem will only occur after reboot and the exact situation depends on the starting order of `mongod` and `mongos` service. If `mongod` starts first, then the problem is reproduced.

P.S. Strictly speaking, the `mongod` service isn't `chkconfig`'d either. But a `chkconfig --list | grep mongo` shows that service is enabled and I think the yum package did that.

**Comment by tonynv** [comment]
@vsnyc If this issue is resolved with the last update please close

**Comment by vsnyc** [comment]
Sharding option has been removed from the quick start. This can be closed
