### ISSUE TITLE
rs.initiate() failed in mongo 3.4

### ISSUE THREAD

**Issue by khiyani** [aws-quickstart/quickstart-mongodb#16]
{
        "ok" : 0,
        "errmsg" : "No host described in new configuration 1 for replica set #### maps to this node",
        "code" : 93,
        "codeName" : "InvalidReplicaSetConfig"
}

**Comment by vsnyc** [comment]
Is this reproducible? Could you provide the parameters used?

**Comment by vsnyc** [comment]
@khiyani, following up on the reported issue. Could you provide the cloudformation template name and parameters used to reproduce this? Thanks.

**Comment by khiyani** [comment]
Hi Vinod,

Thanks for the follow up. The issue has now been fixed.

Regards,
Rohith Khiyani
Associate Professional-Programmer Analyst, Big Data And Analytics

T Extn: 743117
M Mobile: 9014095626

DXC Technology
Building #4, Mindspace,
Hyderabad,500081

dxc.technology<http://www.dxc.technology/> / Twitter<https://twitter.com/dxctechnology> / Facebook<https://www.facebook.com/DXCTechnology/> / LinkedIn<https://www.linkedin.com/company/dxctechnology>

**Comment by vsnyc** [comment]
Great, appreciate the update. I'll resolve it.
