### ISSUE TITLE
Possible buggy code in orchestrator.sh opt parsing 

### ISSUE THREAD

**Issue by Jaspereclipse** [aws-quickstart/quickstart-mongodb#18]
Hi,

When orchestrator.sh tries to parse the opts (see below),  there are two options with the same char "-i" - one used for initiating the environment and the other one used for inserting a new key-pair value into DynamoDB. 

I was trying to modify the code by inserting a new key-pair value during setup but it turned out that `getopts`  cannot tell `-i` from `-i key=value`. 

I would suggest using another character for the insert option (ex. `-u` for update)

```
while getopts "hcbpdgikfs:i:n:q:w:" o; do
  case "${o}" in
    h) usage && exit 0
    ;;
    c) CREATE=1
    ;;
    p) PRINT=1
    ;;
    b) BLOCK_UNTIL_TABLE_LIVE=1
    ;;
    d) DELETE_TABLE=1
    ;;
    g) GET_IPv4_TYPE=1
    ;;
    q) QUERY_STATUS=${OPTARG}
    ;;
    s) NEW_STATUS=${OPTARG}
    ;;
    k) CREATE_KEY=1
    ;;
    f) FETCH_KEY=1
    ;;
    i) NEW_ITEM_PAIR=${OPTARG}
    ;;
    n) TABLE_NAME=${OPTARG}
    ;;
    w) WAIT_STATUS_COUNT_PAIR=${OPTARG}
    ;;
    i) INIT_ENV=1
    ;;
  esac
done
```

**Comment by vsnyc** [comment]
This is fixed. insert/update for new_item_pair key is changed to 'u'
