### ISSUE TITLE
Opening port range 27017-27030

### ISSUE THREAD

**Issue by rcra90** [aws-quickstart/quickstart-mongodb#19]
Is there a reason for opening ports 27017 to 27030 on node instances, when MongoDB only uses 27017-27019 according to this part of the documentation? https://docs.mongodb.com/manual/reference/default-mongodb-port/

If the ports aren't used, isn't it unnecessary to open them?

Line 337-338 in https://github.com/aws-quickstart/quickstart-mongodb/blob/master/templates/mongodb.template

**Comment by vsnyc** [comment]
A previous version of the quick start had the option of creating several micro shards (multiple mongod instances running on a server at different ports) and hence opened up the above port range. I'll revisit the security group setting and see what can be  fixed.

**Comment by vsnyc** [comment]
Closing old issues. This repository is now deprecated in favor of of https://github.com/aws-quickstart/quickstart-mongodb-atlas.
