### ISSUE TITLE
Unable to access Mongo cluster in vpc from web service node

### ISSUE THREAD

**Issue by yuganghu** [aws-quickstart/quickstart-mongodb#2]
I was able to create a mongodb cluster with mongndb-vpc.template with CloudFormation. I can access PrimaryReplicator node on 27017 from ssh, however unable to access from outside, because the only node exposed to public is the NAT node, which did not expose the port 27017 port. Can someone help?

I have web services running in EC2. I am wondering how I can access MongoDB from my EC2 instance (in web service code). Is there other ways than forcing web service nodes and mongo nodes to be in the same subnet?

**Comment by tonynv** [comment]
@vsnyc If this issue is resolved with the last update please close

**Comment by vsnyc** [comment]
Please review the revised architecture guide and [VPC setup.](https://aws.amazon.com/quickstart/architecture/vpc/). Connectivity from EC2 nodes can be achieved by placing them in the private subnets.
