### ISSUE TITLE
Are these templates going to be updated to support sharding on 3.6

### ISSUE THREAD

**Issue by theodore-q** [aws-quickstart/quickstart-mongodb#20]
The mongo sharding template; mongodb-database-sharded.template. only supports mongodb 3.2 and has no outputs. Are there any plans from the amazon team to bring it up-to-date and add outputs?

**Comment by vsnyc** [comment]
The current version of the mongodb quick start (https://aws.amazon.com/quickstart/architecture/mongodb/) only supports building a 3 node replica set cluster.

Setting up a shared replica set is not in scope. I will clean out the repository and remove files that are not in use.

Thanks
Vinod
