### ISSUE TITLE
In public subnet , it is not working

### ISSUE THREAD

**Issue by shree007** [aws-quickstart/quickstart-mongodb#22]
when I am creating my primary in public subnet and secondaries replica in private , it is not working.

any suggestion ?

Thanks

**Comment by vsnyc** [comment]
Ideally you should be running the mongo instances in private subnets. However I tested the setup you mentioned and it worked fine as well (see screenshot below). What kind of issue did you run into? I ran the [AWS VPC quick start](https://aws.amazon.com/quickstart/architecture/vpc/) (for VPC setup), [Linux bastion quick start](https://aws.amazon.com/quickstart/architecture/linux-bastion/) (for bastion host) and then launched the mongodb stack in existing vpc just created and selected public subnet for the primary instance and private subnets for the secondary replica instances.

<img width="980" alt="mongodb-public-private-subnets" src="https://user-images.githubusercontent.com/624297/36766770-56a6bf1a-1c05-11e8-8bde-1eb8bff6633f.png">

**Comment by shree007** [comment]
Actually there were problem with bind ip and security group. I resolved.

Thanks for your valuable answer Sir.

Thanks

Shree Prakash

**Comment by vsnyc** [comment]
Great, I'll close out the issue.
