### ISSUE TITLE
403 Forbidden for s3://quickstart-reference/mongodb/latest/scripts/init.sh

### ISSUE THREAD

**Issue by erincerys** [aws-quickstart/quickstart-mongodb#24]
`orchestrator.sh` and `signalFinalstatus.sh` are fine, but `init.sh` began throwing this error over the weekend. This looks to be an issue on the bucket side, since the template specifies IAM allow for `s3:*` on the instance role.

**Comment by vsnyc** [comment]
That file was deprecated and causing confusion, so I have removed it. How were you using the file? 

See https://github.com/aws-quickstart/quickstart-mongodb/blob/master/templates/mongodb-node.template#L342, the quick start is using init_replica.sh that exists in the repo and in the s3 bucket.

**Comment by erincerys** [comment]
We had copied a previous version of the quickstart template to use in our own system. This deprecation broke new stack creation for our development team since we did not copy the initialization scripts into our own bucket. I have done this now, since we had the files on an existing instance, but this deprecation led to some lost productivity today. I suppose I should not have expected backwards compat.

**Comment by vsnyc** [comment]
It is difficult for us to keep supporting prior versions, although you can fork and tag a particular commit to be on the version you have been using. In addition, if you make modifications that you think are going to benefit the community and would like to contribute back, pull requests are welcome.

We have put some work into making the quick starts portable so you can take the code and stage in your S3 bucket and have it work from there. In particular, `QSS3BucketName` and `QSS3KeyPrefix` parameters can be modified to your S3 bucket and prefix respectively at which at the assets have been uploaded and passed to the cloud formation templates.

Please feel free to open a new issue with any feedback.
