### ISSUE TITLE
Issue with run replicas

### ISSUE THREAD

**Issue by LihoyKozak** [aws-quickstart/quickstart-mongodb#27]
Hello, 

I need your help with set the replicas. 
I have used this template for long time just for 1 node.

Now I need to create replicas. But when I set the Cluster Replica Set Count from 1 to 3, cloudformation create instances but cannot create replicas. Also it cannot cleanup, and then delete my replica nodes.

Changes:
![screen shot 2018-03-22 at 5 55 58 pm](https://user-images.githubusercontent.com/24983515/37782108-c5b779ec-2dfa-11e8-9cd0-1ea0ffa07e03.png)

From main stack:
![screen shot 2018-03-22 at 5 56 53 pm](https://user-images.githubusercontent.com/24983515/37782190-fe90757a-2dfa-11e8-9a93-32a4e7da6009.png)

At PrimaryReplicaNode0
![screen shot 2018-03-22 at 5 58 02 pm](https://user-images.githubusercontent.com/24983515/37782493-aac4580c-2dfb-11e8-90c8-286f889b8e84.png)

At SecondaryReplicaNode0 everything is ok (CREATE_COMPLETE)

**Comment by LihoyKozak** [comment]
Understand now. I can create stack with 1 or 3 nodes. But can't create stack with 1 node and then increase it to 3 nodes.

**Comment by renatomjr** [comment]
It would be great if we could start with 1 node and then upgrade to 3 without recreating the stack.

**Comment by vsnyc** [comment]
It is difficult to do that with a cloudformation update command. If you already have a 1 node stack up, then you could use launch the mongodb-node.template twice to spin up two new nodes in the same VPC and then join the new instances with the current 1 node as a replica set. Read more here: https://docs.mongodb.com/v3.4/tutorial/expand-replica-set/
