### ISSUE TITLE
Q: Reattach existing volumes

### ISSUE THREAD

**Issue by willks** [aws-quickstart/quickstart-mongodb#30]
Thanks for the scripts. Is there a scenario for a "host death" to handle re-attaching existing data volumes like StatefulSets in Kubernetes? Seriously, in my line of work I've got to handle both. When server dies in GCP GKE, we just re-attach to existing Stateful drive automatically. Could not find a procedure here to handle that scenario in  AWS. Any help appreciated (through CloudFormation).

**Comment by Bessonov** [comment]
Unfortunately, I think this is not possible on aws automatically. Instead of this you can use aws cli to discover, create and mount volumes in EC2's UserData/Cloud::Init with AutoScalingGroup. A lite version for static EC2 would be like (pseudo code):

```
MyVolume:
    Type: AWS::EC2::Volume
[...]
```
And for EC2-Instance:
```
[...]
      Volumes:
        -
          VolumeId: !Ref MyVolume
          Device: /dev/xvdf
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          yum -y update

          # prepare mount volume
          # copied from mongo quickstart
          yum install -y xfsprogs
          echo "/dev/xvdf /data xfs defaults,auto,noatime,noexec 0 0" | tee -a /etc/fstab
          if ! lsblk -f | grep xvdf | grep xfs; then
            mkfs.xfs -f /dev/xvdf
          fi
          blockdev --setra 32 /dev/xvdf
          mkdir -p /data
          mount -a
          rm -rf /etc/udev/rules.d/85-ebs.rules
          touch /etc/udev/rules.d/85-ebs.rules
          echo 'ACTION=="add", KERNEL=="'$1'", ATTR{bdi/read_ahead_kb}="16"' | tee -a /etc/udev/rules.d/85-ebs.rules
          echo "* soft nofile 64000
          * hard nofile 64000
          * soft nproc 32000
          * hard nproc 32000" > /etc/limits.conf

          yum install -y aws-cfn-bootstrap
          /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource MyInstance --region ${AWS::Region} --configsets InstallAndRun
          /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource MyInstance --region ${AWS::Region}
[...]
```

**Comment by vsnyc** [comment]
@willks In this case, the mongodb instances are setup with [EC2 auto-recovery](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-recover.html) so that should automatically happen.
