### ISSUE TITLE
Problem with updating yum, when deploying in private subnet

### ISSUE THREAD

**Issue by daniyel** [aws-quickstart/quickstart-mongodb#33]
Hi.

I adopted the CloudFormation templates a little bit since I already have VPC set up and I do not need bastion Host so basically I would like to deploy one instance on development environment and 1 primary and 2 secondary for production. I am trying to deploy everything in private subnet, but my deploy always fail with `The following resource(s) failed to create: [PrimaryReplicaNode0WaitForNodeInstall]. . Rollback requested by user.` and `WaitCondition timed out. Received 0 conditions when expecting 1`. I have also checked logs from ec2 instance and I have problem with updating the AMI Linux with yum. Since it is private subnet they have NAT gateway attached and also I have checked about VPC endpoint and I have set up that as well but nothing helped. I have checked NACL as well and Inbound is open to 0.0.0.0/0 to all ports. I do not know what else I can try.

Best regards.

**Comment by vsnyc** [comment]
Could you post the logs showing failure messages? Is it failing for mongodb installation or even before that at `yum -y update`? Does the instance have internet connectivity?

**Comment by viniciusnz** [comment]
Same here...

![screenshot from 2018-07-11 23-37-00](https://user-images.githubusercontent.com/1224288/42609521-62419170-8563-11e8-9b91-96ec3d997b62.png)

I waited for one hour and it didn't go... Using an s3 copy of the master of this repo...

**Comment by vsnyc** [comment]
@viniciusnz Did it fail for you also at `yum -y update`? For troubleshooting this further, could you disable CloudFormation rollback so you can go into the EC2 instances and inspect `cfn-*` log files in `/var/log/` on the three instances, you can start with the primary replica node?

Further, I'd just add that we tests the quick starts regularly, this quick start is passing successfully in multiple regions and this is not a known issue. Having the logs will help troubleshoot what is going on. Thanks!
