### ISSUE TITLE
Q: Is there a way to create encrypted ebs volumes

### ISSUE THREAD

**Issue by matt-croft** [aws-quickstart/quickstart-mongodb#34]
When using the cloud formation template there is no way to set the volumes to be encrypted from what i can tell, is there a way to do this after creation if created?

Or is there an easier way to modify the stack to add this in?

**Comment by vsnyc** [comment]
Right now the quick start template does not provide this option, though I think it will be a good addition. 

The easiest way to accomplish this would be to add `Encrypted: True` property to the BlockDeviceMappings section for the three configured EBS volumes prior to launching the template.

https://github.com/aws-quickstart/quickstart-mongodb/blob/b6cf713d9a91c5c1092e69d317c653e85994b04f/templates/mongodb-node.template#L284-L293

Encrypting the EBS volumes after creation is a bit involved, you have to take a snapshot, encrypt it and reattach.

**Comment by matt-croft** [comment]
Thanks for you the reply, i looked into this and after doing some reading i was able to produce the stack with encrypted EBS volumes, 

Would be nice to see this get added soon.

**Comment by vsnyc** [comment]
I've added Encryption to EBS volumes at commit: https://github.com/aws-quickstart/quickstart-mongodb/commit/4c8b44c6f406b1a607c591b8abf951e759dad6c7
