### ISSUE TITLE
Master merge appears to have lost scripts/disable-transparent-hugepages

### ISSUE THREAD

**Issue by alphafoobar** [aws-quickstart/quickstart-mongodb#35]
This appears to be still required here: https://github.com/aws-quickstart/quickstart-mongodb/blob/master/templates/mongodb-node.template#L366

Was this intentionally removed?

**Comment by vsnyc** [comment]
Thanks for pointing this out. Yes the file should be there, I'll add it shortly.

**Comment by vsnyc** [comment]
Fixed at commit 3c2d9ee0aa3a4f90198ad287eed576cf5945a66a
