### ISSUE TITLE
BastionSecurityGroup creation failed for unknown reason 

### ISSUE THREAD

**Issue by likedan** [aws-quickstart/quickstart-mongodb#38]
I'm trying to create a mongo cluster on a new VPC. Somehow, the script always fail as this error, which I don't understand why.

CREATE_FAILED | AWS::CloudFormation::Stack | BastionStack | Embedded stack arn:aws:cloudformation:us-east-1:139587094038:stack/FashionMongoDB-BastionStack-YKHO65CGR2OP/e49790d0-cc48-11e8-b1c6-503aca2616fd was not successfully created: The following resource(s) failed to create: [BastionSecurityGroup, EIP1].
-- | -- | -- | --

**Comment by vsnyc** [comment]
Could you post the full log? It is possible that you are hitting a limit error and may have to put in a request to increase the number of Elastic IPs for your account.

**Comment by likedan** [comment]
It somehow worked once I switched to a different reason. There must be some weird configuration with that particular region. Thanks!
