### ISSUE TITLE
Can't change Volume size?

### ISSUE THREAD

**Issue by likedan** [aws-quickstart/quickstart-mongodb#39]
<img width="1734" alt="screen shot 2018-11-02 at 12 58 59 am" src="https://user-images.githubusercontent.com/8799955/47896236-82479980-de3a-11e8-894b-df10cfe32ea7.png">
Somehow I can upgrade the EBS volume size through the stack, each time I try to do so, I get rolled back. I can make other change such as changing the instance type. Can't figure out what's the problem with upgrading volume.

**Comment by proton1k** [comment]
@likedan did you find out? Was the issue related to drift-detection?

**Comment by vsnyc** [comment]
Closing old issues. This repository is now deprecated in favor of of https://github.com/aws-quickstart/quickstart-mongodb-atlas.
