### ISSUE TITLE
S3 error: Access Denied - when running template through CloudFormation web Console

### ISSUE THREAD

**Issue by tioback** [aws-quickstart/quickstart-mongodb#40]
I'm getting the following message when I try to run the template through CloudFormation's web console:

    S3 error: Access Denied For more information check 
    http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html

I tried filling out the form in two different ways: providing a new s3 bucket and prefix and providing existing bucket and prefix. Still I got the same error and the result was a rollback.

Any ideas?

**Comment by vsnyc** [comment]
Need more detail on this. When you launch the Quick Start from the official launch page:
https://aws.amazon.com/quickstart/architecture/mongodb/

You can choose one of these two options and you can keep the default bucket names, don't have to provide your own.

1. [Deploy into a new VPC](https://fwd.aws/Kxy33)
2. [Deploy into your existing VPC](https://fwd.aws/av6d6)

<img width="891" alt="screen shot 2018-12-06 at 10 28 03 pm" src="https://user-images.githubusercontent.com/624297/49626106-4ad28c80-f9a6-11e8-80e1-2f298df05b04.png">

In the CloudFormation console, you will the default values populated, you can keep that as these already host the assets.
<img width="549" alt="screen shot 2018-12-06 at 10 29 11 pm" src="https://user-images.githubusercontent.com/624297/49626162-8c633780-f9a6-11e8-9a8b-8d5c332e6c68.png">

If you are launching the Quick Start from your own bucket, then follow these steps in the Quick Start Contributor's Guide: [Make the Quick Start your own](https://aws-quickstart.github.io/option1.html)

**Comment by lecong** [comment]
I have the same error

I download this repo upload to my bucket with folder name quickstart-mongodb but error not resolve

Please help me fix it
