### ISSUE TITLE
Problem with scripts deploying MongoDb on the instances

### ISSUE THREAD

**Issue by anderspalm** [aws-quickstart/quickstart-mongodb#43]
When I deploy the CFT from the link provided in the Quick Start documentation, the IGW, VPC, Subnets, Bastion, and Instances spin up fine. What I don't see is any MongoDB database having been installed on the instance(s). 

I tried to run the shell commands that are present in the mongodb-node.yaml file manually in the master EC2 instance and I ran into access denied (so I changed the commands to sudo). The next issue was a lack of permissions for the bastion host seen below.

1) An error occurred (UnauthorizedOperation) when calling the DescribeTags operation: You are not authorized to perform this operation.
 - I added this and it moved on

2) An error occurred (AccessDeniedException) when calling the Scan operation: User: arn:aws:sts::799480191532:assumed-role/MongoDBDefaultTemplate-BastionStac-BastionHostRole-ZGYB178JU1YI/i-0e27c1187822d2d72 is not . 
- I added this and it moved on

Then the init.sh completes but upon running the database it says that it is unable to find the server.

Is there anything I am not understanding about this deployment? Please let me know if you need logs or any details for a better understanding of my situation, all help would be greatly appreciated.

Thanks

**Comment by youssefxyz** [comment]
Same problem here  

Any insight ????

**Comment by vsnyc** [comment]
I just tested this and wasn't able to reproduce the error. 

Stack creation:
![Screen Shot 2019-03-22 at 3 58 17 PM](https://user-images.githubusercontent.com/624297/54849699-66467680-4cbb-11e9-87ac-450aa201ce5d.png)

Verification steps:
1. Add the key pair to my ssh agent so I don't have to copy it to the bastion host.
2. Login to the bastion host using ec2-user and IP address of the bastion host published in outputs section of the bastion stack. I added the external IP to my hosts file as mongo-bastion.local.
3. Login to the primary mongodb instance (IP address in primary stack output)
4. Login to mongo console and execute `printReplicationInfo()` and `status()` methods. 

![Screen Shot 2019-03-22 at 4 07 59 PM](https://user-images.githubusercontent.com/624297/54850349-4617b700-4cbd-11e9-80ce-0ab010872f37.png)

**Comment by vsnyc** [comment]
@anderspalm and @youssefxyz 

Could you provide more info about your setup? Did you deploy the standard 3-node replica set that I tested above? Please provide the following information to troubleshoot further:

1. Parameters used to deploy the stack. If you use the aws cli and [jq](https://stedolan.github.io/jq/) tool, the following command will give that information. If not using jq, you can copy the parameters part from the output of `describe-stacks` call.
`aws cloudformation describe-stacks --stack <YOUR_STACK_NAME> --region <YOUR_REGION> | jq '.Stacks|.[]|.Parameters'`

2. The following files from all three mongodb nodes: primary, secondary0 and secondary1:
    * cfn-init-cmd.log  cfn-init.log  cfn-wire.log  cloud-init.log  cloud-init-output.log in /var/log
    * /home/ec2-user/mongodb/install.log

**Comment by anderspalm** [comment]
Hi Vinod, thanks for reaching out. 

I followed as you said, it was what we have already done and it worked fine, so I am not sure why it did not work for my colleagues and I last week. The only change was setting the --password and --username parameters when entering the mongo console.

**Comment by vsnyc** [comment]
@anderspalm thanks, appreciate the confirmation.

@youssefxyz I'll proceed to resolve this, feel free to open a new issue with more information.
