### ISSUE TITLE
Is there a way to change the storage engine from “wiredTiger” to “mmapv1”?

### ISSUE THREAD

**Issue by busylee** [aws-quickstart/quickstart-mongodb#44]
The storage engine of MongDB on my instance looks “wiredTiger”.  but I want to change the storage engine from “wiredTiger” to “mmapv1”.
Is there anyone who can help me? please guide for me.

**Comment by vsnyc** [comment]
Closing old issues. This repository is now deprecated in favor of of https://github.com/aws-quickstart/quickstart-mongodb-atlas.
