### ISSUE TITLE
MongoDB QuickStart timeout and rollback

### ISSUE THREAD

**Issue by mzarnawski** [aws-quickstart/quickstart-mongodb#46]
Currently Mongo DB deployment times out at node creation. The reason for this is that node template attempts to copy some files from S3 bucket to which it has no access.
For example EC2 instance has access policy to S3 bucket aws-quickstart-eu-central-1 and bootstrap scripts attempts to download script from bucket aws-quickstart. As a result bootstrap script fails, signal final status is never executed and the whole stack is rolled back when timeout is reached.

I found that similar issue was reported here although I don't know if the root cause is the same..
https://forums.aws.amazon.com/thread.jspa?messageID=936559

**Comment by vsnyc** [comment]
@mzarnawski Thanks for reporting this. We recently did a change, see commit: https://github.com/aws-quickstart/quickstart-mongodb/commit/75313beb8a5297b9f4a10962b997c1d9c4e6b45f to use regional buckets and S3 SigV4 that has resulted in this. I have added a fix: https://github.com/aws-quickstart/quickstart-mongodb/commit/3938ab1846fd2c342b6dbe56df93998dd1bdf3f9 to resolve this. The change will automatically merge to master branch and push to the live Quick Start links once testing is complete.

**Comment by mzarnawski** [comment]
Thanks @vsnyc 
That should work. I hope you merge this soon because as of now, Mongo DB stack cannot be deployed unless fixed locally.

**Comment by mzarnawski** [comment]
BTW, don't you think it would be reasonable to disable the link on QuickStarts web page:
https://docs.aws.amazon.com/quickstart/latest/mongodb/welcome.html
or give some warning in the situation when you know that it is not going to work ?

**Comment by vsnyc** [comment]
@mzarnawski The change is merged and deployed to S3, please retry.

**Comment by vsnyc** [comment]
> BTW, don't you think it would be reasonable to disable the link on QuickStarts web page:
> https://docs.aws.amazon.com/quickstart/latest/mongodb/welcome.html
> or give some warning in the situation when you know that it is not going to work ?

That should usually not happen. The master branch code is the one that has passed our testing.  In this case, looks like the CloudFormation templates had passed without error. We do periodically test all quick starts. See the [latest run](https://s3.amazonaws.com/aws-quickstart-reports/develop/quickstart-mongodb/index.html).

**Comment by mzarnawski** [comment]
@vsnyc You should really check the tests and/or testing environment because there is no way that the changes deployed on 14th March could pass the tests - they should fail 100% cases.

Also I think you should follow the contributing guidelines for this repo and create an issue for the problem you are working on. Because if you don't, there is no way of knowing for me that this is a known issue that is being worked on.
Also I don't see a PR for what you merged.

**Comment by vsnyc** [comment]
> @vsnyc You should really check the tests and/or testing environment because there is no way that the changes deployed on 14th March could pass the tests - they should fail 100% cases.
> 

@mzarnawski - appreciate the feedback. So there are two items to discuss and address here. 
1. The changes deployed on March 14th did indeed pass CloudFormation test (i.e. stack was successfully created) and hence got merged and pushed. The fact that the mongodb cluster wasn't operational after the install didn't get caught, which leads to my next point.
2. We could have had better error handling in the script to fail the stack if the file couldn't be pulled from S3 due to access restriction. I have opened a new [issue](https://github.com/aws-quickstart/quickstart-mongodb/issues/47) for this.

> Also I think you should follow the contributing guidelines for this repo and create an issue for the problem you are working on. Because if you don't, there is no way of knowing for me that this is a known issue that is being worked on.
> Also I don't see a PR for what you merged.

This is a fair comment. I'll adhere to it in the future.

**Comment by mzarnawski** [comment]
Ad. 1 
This is so strange because for me only the nested stack was completed and parent stack was not completed and finally rolled back after timeout. So again some more checks would be needed in the tests.
