### ISSUE TITLE
Add support for MongoDB 4.2

### ISSUE THREAD

**Issue by vsnyc** [aws-quickstart/quickstart-mongodb#50]
Add support for MongoDB 4.2

**Comment by ismailyenigul** [comment]
Hi,

I modifed the template for Amazon Linux 2 with mongodb 4.2 
I submitted a PR and it is available in my fork at https://github.com/ismailyenigul/quickstart-mongodb/tree/mongo42-amazonlinux2

**Comment by vsnyc** [comment]
Thank you @ismailyenigul - I'll review the PR.

**Comment by vsnyc** [comment]
Addressed in PRs #55 and #58
