### ISSUE TITLE
Why all the AMIs are customized instead of standard Linux AMI?

### ISSUE THREAD

**Issue by salander0411** [aws-quickstart/quickstart-mongodb#53]
This is not an issue actually.. wondering why all the AMIs are customized community AMIs? How are the AMIs different from standard ones, say any pre-installed softwares?

I have tried to launch it in standard AMIs but failed, it seems auto scaling cannot receive cfn success signal. Could you kindly explain on that? Thanks!

**Comment by vsnyc** [comment]
> wondering why all the AMIs are customized community AMIs?

We're not using customized community AMI, instead we're using standard Amazon Linux AMI to do the deployment.

> I have tried to launch it in standard AMIs but failed, it seems auto scaling cannot receive cfn success signal. Could you kindly explain on that?

Not sure, which AMI did you try?

**Comment by salander0411** [comment]
For example, in linux-bastion.template,  the AMI mapping is 

[us-east-1]
AMZNLINUX2: ami-0a887e401f7654935
AMZNLINUXHVM: ami-0e2ff28bfb72a4e45

both of which are community AMI. The standard AMI in this region is ami-0323c3dd2da7fb37d  for AMAZON LINUX 2.

**Comment by vsnyc** [comment]
> both of which are community AMI. The standard AMI in this region is ami-0323c3dd2da7fb37d for AMAZON LINUX 2.

This is not quite right. Taking Amazon Linux 2 as an example both `ami-0a887e401f7654935` and `ami-0323c3dd2da7fb37d` are standard Amazon Linux 2 AMIs. `ami-0323c3dd2da7fb37d` happens to be the latest one, released on April 4. `ami-0a887e401f7654935` was released on February 12.

We do have an automated process that updates the AMIs periodically. We can check why the bastion quick start hasn't updated to the latest. If I recall the logic was picking the latest across all AWS Regions, so sometimes it would keep an older version if that remained the latest in a few.

Here's the output of `describe-images` CLI command that should help.

```
$ aws ec2 describe-images --image-id ami-0a887e401f7654935
{
    "Images": [
        {
            "Architecture": "x86_64",
            "CreationDate": "2020-02-12T09:07:16.000Z",
            "ImageId": "ami-0a887e401f7654935",
            "ImageLocation": "amazon/amzn2-ami-hvm-2.0.20200207.1-x86_64-gp2",
            "ImageType": "machine",
            "Public": true,
            "OwnerId": "137112412989",
            "State": "available",
            "BlockDeviceMappings": [
                {
                    "DeviceName": "/dev/xvda",
                    "Ebs": {
                        "DeleteOnTermination": true,
                        "SnapshotId": "snap-03a475f314b035167",
                        "VolumeSize": 8,
                        "VolumeType": "gp2",
                        "Encrypted": false
                    }
                }
            ],
            "Description": "Amazon Linux 2 AMI 2.0.20200207.1 x86_64 HVM gp2",
            "EnaSupport": true,
            "Hypervisor": "xen",
            "ImageOwnerAlias": "amazon",
            "Name": "amzn2-ami-hvm-2.0.20200207.1-x86_64-gp2",
            "RootDeviceName": "/dev/xvda",
            "RootDeviceType": "ebs",
            "SriovNetSupport": "simple",
            "VirtualizationType": "hvm"
        }
    ]
}

$ aws ec2 describe-images --image-id  ami-0323c3dd2da7fb37d
{
    "Images": [
        {
            "Architecture": "x86_64",
            "CreationDate": "2020-04-07T17:30:33.000Z",
            "ImageId": "ami-0323c3dd2da7fb37d",
            "ImageLocation": "amazon/amzn2-ami-hvm-2.0.20200406.0-x86_64-gp2",
            "ImageType": "machine",
            "Public": true,
            "OwnerId": "137112412989",
            "State": "available",
            "BlockDeviceMappings": [
                {
                    "DeviceName": "/dev/xvda",
                    "Ebs": {
                        "DeleteOnTermination": true,
                        "SnapshotId": "snap-0e1167baa50e9c0ff",
                        "VolumeSize": 8,
                        "VolumeType": "gp2",
                        "Encrypted": false
                    }
                }
            ],
            "Description": "Amazon Linux 2 AMI 2.0.20200406.0 x86_64 HVM gp2",
            "EnaSupport": true,
            "Hypervisor": "xen",
            "ImageOwnerAlias": "amazon",
            "Name": "amzn2-ami-hvm-2.0.20200406.0-x86_64-gp2",
            "RootDeviceName": "/dev/xvda",
            "RootDeviceType": "ebs",
            "SriovNetSupport": "simple",
            "VirtualizationType": "hvm"
        }
    ]
}
```

**Comment by salander0411** [comment]
Got it! Thanks so much for your explanation
