### ISSUE TITLE
S3 error: Access Denied

### ISSUE THREAD

**Issue by alejandro-kid** [aws-quickstart/quickstart-mongodb#54]
I created a role with full access to VPC, S3 and especific S3::bucket created to store data, and this error still appear:
Logical ID   |           Status             |                                  Status reason

VPCStack   | CREATE_FAILED    |  S3 error: Access Denied For more information check http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html

**Comment by vsnyc** [comment]
If you are trying to launch from your own S3 bucket, this should help: https://aws-quickstart.github.io/option1.html.

What was the role for, to launch CloudFormation template? If yes, you'll need more access than just VPC and S3.
