### ISSUE TITLE
Handling change of AZs number

### ISSUE THREAD

**Issue by mzarnawski** [aws-quickstart/quickstart-mongodb#57]
After the Mongo stack (version with with new VPC) is created, subsequent update of the stack with increase of the AZs from 2 to 3 results in the following behaviour:
- one of the Mongo secondary replicas is created in the new availability zone and the old one is terminated
- the whole stack update finishes with success (false positive)
- the newly created replica is not fully functional, the orchestrator script loops waiting for DynamoDB table which does not exist (this table is usually created at the first stack creation when all Mongo nodes are being created, to synchronize the process of creating the nodes)

So currently the sh scripts don't handle the case of a node being recreated.

The workaround for this is:
1. Log in to the new Mongo instance. Check install.log
2. Add the table named s0_MONGODB__YourMongoStackName_YourVpcID for example using script:
aws dynamodb create-table \
        --table-name ${TABLE_NAME} \
        --attribute-definitions \
            AttributeName=PrivateIpAddress,AttributeType=S \
        --key-schema \
            AttributeName=PrivateIpAddress,KeyType=HASH \
        --provisioned-throughput ReadCapacityUnits=1,WriteCapacityUnits=1
3. Add Mongo instances IPs to the table with field Status=WORKING. Check install.log, change Status to FINISHED and then SECURED. Wait for scripts to end.
4. Copy authorization key from other Mongo replica to the new one
5. Log in to Mongo. Rebuild the replica set: 
cfg = rs.conf()
cfg.members[index_of_old_secondary_replica].host = "IP_OF_THE_NEW_REPLICA:27017"
rs.reconfig(cfg)

**Comment by vsnyc** [comment]
@mzarnawski  - Thanks, Mikolaj! This is very helpful information, thank you for documenting this.

**Comment by mzarnawski** [comment]
@vsnyc May I know what is the reason for closing this ? Is it solved, or not worth solving or do you think the workaround is just enough ?

**Comment by vsnyc** [comment]
@mzarnawski This quick start does not support CloudFormation stack update operation, there are several unknowns and what you've figured out is just one of several use cases where it does not work by default. It would certainly be worth solving holistically, but the update behavior for CloudFormation is heavily dependent on the update operation of the underlying resources. And given the stateful nature of this solution, it is hard to make it work for all combinations. Thus, for the use case you documented, I think that the workaround is enough.

**Comment by mzarnawski** [comment]
@vsnyc Thanks ! I appreciate your letting me know.
