### ISSUE TITLE
4.0 works but 4.2 does not with the same parameters

### ISSUE THREAD

**Issue by HatBeardZero** [aws-quickstart/quickstart-mongodb#60]
I tried setting up 2 stacks, one with 4.0 and one with 4.2 and the 4.2 consistently fails, where the 4.0 works the first time.

i'm using the existing vpc option.

WaitCondition timed out. Received 0 conditions when expecting 1

The following resource(s) failed to create: [PrimaryReplicaNode0WaitForNodeInstall, SecondaryReplicaNode0WaitForNodeInstall, SecondaryReplicaNode1WaitForNodeInstall]. . Rollback requested by user.

**Comment by vsnyc** [comment]
This is not reproducible, in our CI we are testing with 4.2 as the default option and that works for us. I also tested it manually and wasn't able to reproduce the error. Can you test this in a new VPC possibly in a different region to ensure it's not something within your VPC/account limits that is causing the error?


![Screen Shot 2020-08-10 at 5 23 38 PM](https://user-images.githubusercontent.com/624297/89849157-e0e49000-db55-11ea-9a75-b5081a9d2d1b.png)
