### ISSUE TITLE
Installation unsuccessful while using mongo v3.6 [both existing vpc and new vpc mode]

### ISSUE THREAD

**Issue by Kadan7** [aws-quickstart/quickstart-mongodb#64]
I met installation error while using this to install mongo 3.6, in us-east-1 and us-east-2, with existing vpc and new vpc mode:
1. the primary node and secondary node can be launched
2. logon with ssh, no mongo was installed
3. cloudformation error swith omething like "waitforinstallation handler"

however, it was success with version 4.2

**Comment by vsnyc** [comment]
@Kadan7 - thanks for the report. It is possible that something has changed when we moved to Amazon Linux 2 and v4.2 as the default. Looking at the PR: https://github.com/aws-quickstart/quickstart-mongodb/pull/55/files, I think it is the `baseurl` path. 

http://repo.mongodb.org/yum/amazon/2/mongodb-org/3.6/x86_64/ does not exist.

**Comment by vsnyc** [comment]
This has been fixed in PR #65. Please retry and open a new issue if you run into anything else.
