### ISSUE TITLE
How to call all the parameters in put given in main deployment new /exiting yaml 

### ISSUE THREAD

**Issue by abinasroy** [aws-quickstart/quickstart-mongodb#66]
please give a sample how to execute the yaml with input parameters.

**Comment by abinasroy** [comment]
any update?

**Comment by vsnyc** [comment]
@abinasroy - It is the same process that you would normally use to pass the parameters to any CloudFormation template. See  the [API documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_CreateStack.html) and [CLI reference](https://docs.aws.amazon.com/cli/latest/reference/cloudformation/create-stack.html). 

In short, if using the AWS CLI, it would look like below. Change the region and stack-name values to match your environment.

```
aws cloudformation --region us-east-1 create-stack --stack-name mongo-test \
  --template-url https://aws-quickstart.s3.amazonaws.com/quickstart-mongodb/templates/mongodb-new-vpc.template.yaml \
  --parameters file://mongodb-params.json \
  --capabilities "CAPABILITY_AUTO_EXPAND" "CAPABILITY_IAM" \
  --disable-rollback
```

Where, the referenced `mongodb-params.json` file will contain the parameter inputs, the minimum required parameters are shown below. 
```
[
    {
        "ParameterKey": "AvailabilityZones",
        "ParameterValue": "us-east-1a,us-east-1b,us-east-1c"
    },
    {
        "ParameterKey": "KeyPairName",
        "ParameterValue": "YOUR_KEY"
    },
    {
        "ParameterKey": "MongoDBAdminPassword",
        "ParameterValue": "CHOOSE_PASSWORD"
    },
     {
        "ParameterKey": "NumberOfAZs",
        "ParameterValue": "3"
    },
    {
        "ParameterKey": "RemoteAccessCIDR",
        "ParameterValue": "MY_PUBLIC_IP_ADDRESS/32"
    }
]
```

You can add any more parameters as needed.  I have also attached a file: [mongodb-all-params.json.txt](https://github.com/aws-quickstart/quickstart-mongodb/files/5492089/mongodb-all-params.json.txt)
 containing all the parameters that you can customize to match your environment and use as input.

**Comment by vsnyc** [comment]
Closing this as answered.
