### ISSUE TITLE
mongodb.template is not compatible with China mainland regions

### ISSUE THREAD

**Issue by lzh88998** [aws-quickstart/quickstart-mongodb#67]
There are hard coded service principal and partition in code. Which lead to failure during deployment in China mainland region.

Replace the following code in mongodb.template:

"ec2.amazonaws.com"
replace with:
{"Fn::Sub":"ec2.${AWS::URLSuffix}"}

"Fn::Sub": "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/*MONGODB_*"
replace with:
"Fn::Sub": "arn:${AWS::Partition}:dynamodb:${AWS::Region}:${AWS::AccountId}:table/*MONGODB_*"

And also replace following code in mongodb-node.template
"arn:aws:automate:",
replace with
 {"Fn::Sub": "arn:${AWS::Partition}:automate:"},

**Comment by vsnyc** [comment]
@lzh88998  - thanks for reporting. Would you be willing to test the suggested edits and make a pull request?  See our [contributor's guide](https://aws-quickstart.github.io/option2.html) for details.

**Comment by salander0411** [comment]
Hi  @vsnyc , please check https://github.com/nwcdorg/quickstart-mongodb for deployment in China regions [BJS & ZHY]

**Comment by vsnyc** [comment]
Closing old issues. This repository is now deprecated in favor of of https://github.com/aws-quickstart/quickstart-mongodb-atlas.
