### ISSUE TITLE
It is throwing up error in Mumbai Region 

### ISSUE THREAD

**Issue by kumar0** [aws-quickstart/quickstart-mongodb#71]
Hi 

I have tried this CF template for Mumabi region but didnt work. for us-west-1 it worked.

**Comment by vsnyc** [comment]
@kumar0 It works fine in our testing. What was the error you encountered?

**Comment by kumar0** [comment]
Probably its AZ problem 
I have tried with all in same AZ ap-south-1c it worked... guess its 1a error

![image](https://user-images.githubusercontent.com/5521144/99640379-b5205280-2a40-11eb-9926-8c18ae53e849.png)


![image](https://user-images.githubusercontent.com/5521144/99633954-a2ede680-2a37-11eb-88ad-d3f2303eea00.png)

**Comment by kumar0** [comment]
Probably its AZ problem 
I have tried with all in same AZ ap-south-1c it worked... guess its 1a error

![image](https://user-images.githubusercontent.com/5521144/99640379-b5205280-2a40-11eb-9926-8c18ae53e849.png)


![image](https://user-images.githubusercontent.com/5521144/99633954-a2ede680-2a37-11eb-88ad-d3f2303eea00.png)

**Comment by kumar0** [comment]
Issues was with AZ not the code
