### ISSUE TITLE
Add support for 4.4

### ISSUE THREAD

**Issue by emilian-kolev** [aws-quickstart/quickstart-mongodb#73]
Hello,

Would it be possible to update the template and add support for MongoDB 4.4?

**Comment by sadecesabri** [comment]
is there any info about the support of MongoDB v4.4 of this template ? 
thanks.

**Comment by vsnyc** [comment]
Closing old issues. This repository is now deprecated in favor of of https://github.com/aws-quickstart/quickstart-mongodb-atlas.
