### ISSUE TITLE
DynamoDB tables are not dropped

### ISSUE THREAD

**Issue by Energon89** [aws-quickstart/quickstart-mongodb#74]
Hello. Thanks for your work. 
We found some flaw)
We created a stack, then deleted it, and wanted to create another one with the same name and vpс. However, we got an error, because the instance was trying to connect to the wrong IP address. It turns out DynamoDB tables are not dropped when the stack is deleted. When we dropped the old tables, the problem was resolved.
Please pay attention to this.

**Comment by vsnyc** [comment]
Closing old issues. This repository is now deprecated in favor of of https://github.com/aws-quickstart/quickstart-mongodb-atlas.
