### ISSUE TITLE
Documentation Error: m3.medium type does not work for single replica node configuration. 

### ISSUE THREAD

**Issue by michaelfortunato** [aws-quickstart/quickstart-mongodb#77]
When configuring the template, if you select the ec2 type to be m3.medium, the cloudformation will fail to create the primary replica node. I suggest m3.medium be removed from the choice of ec2 types. 

Here are the parameters you can use for the template to recreate the error.
AvailabilityZones | us-east-2a,us-east-2b | -
-- | -- | --
BastionAMIOS | Amazon-Linux2-HVM | -
BastionInstanceType | t3.micro | -
ClusterReplicaSetCount | 1 | -
Iops | 100 | -
KeyPairName | ** | -
MongoDBAdminPassword | ** | -
MongoDBAdminUsername | ** | -
MongoDBVersion | 4.2 | -
NodeInstanceType | m3.medium | -
NumBastionHosts | 1 | -
NumberOfAZs | 2 | -
PrivateSubnet1CIDR | 10.0.0.0/19 | -
PrivateSubnet2CIDR | 10.0.32.0/19 | -
PrivateSubnet3CIDR | 10.0.64.0/19 | -
PublicSubnet1CIDR | 10.0.128.0/20 | -
PublicSubnet2CIDR | 10.0.144.0/20 | -
PublicSubnet3CIDR | 10.0.160.0/20 | -
QSS3BucketName | aws-quickstart | -
QSS3BucketRegion | us-east-1 | -
QSS3KeyPrefix | quickstart-mongodb/ | -
RemoteAccessCIDR | 0.0.0.0/0 | -
ReplicaShardIndex | 0 | -
VPCCIDR | 10.0.0.0/16 | -
VolumeSize | 400 | -
VolumeType | gp2

**Comment by vsnyc** [comment]
Closing old issues. This repository is now deprecated in favor of of https://github.com/aws-quickstart/quickstart-mongodb-atlas.
