### ISSUE TITLE
init.sh script failing with AccessDenied for DynamoDB:scan

### ISSUE THREAD

**Issue by AshNat12** [aws-quickstart/quickstart-mongodb#78]
We are running the init_replica.sh script manually inside the server , We see that Script is throwing exception 

An error occurred (AccessDeniedException) when calling the Scan operation: User: arn:aws:sts::xxx:assumed-role/MongoNode-dev/i-xxx is not authorized to perform: dynamodb:Scan on resource: arn:aws:dynamodb:us-east-1:xxx:table/MongoNode-dev

EC2  iam role has all the DynamoDB permissions.

Please help on the issue

**Comment by vsnyc** [comment]
Closing old issues. This repository is now deprecated in favor of of https://github.com/aws-quickstart/quickstart-mongodb-atlas.
