### ISSUE TITLE
quickstart failing while creating mongoDB RS

### ISSUE THREAD

**Issue by Anoop-k-c** [aws-quickstart/quickstart-mongodb#79]
We are facing issue while deploying quickstart along with customized json templates. 

The MongoDB child stack is failing to send a success message (signalFinalStatus) back  to parent stack to complete setup.
Due to this, the parent stack will fail with an error "WaitCondition timedout". 

DynamoDb endpoint from target VPC were removed. However we are able to create the resources without DynamoDB endpoint, but sometime it is failing with error.
Since it is not consistent with behavior, need your help to understand the role of DynamoEndpoint and how Quickstart setup is connected with the same.

Thanks in advance.

![Capture](https://user-images.githubusercontent.com/97510921/148915148-fcae0b14-f9dd-44e9-b653-4510dc097a1a.JPG)

**Comment by vsnyc** [comment]
Closing issue, this repository is now deprecated in favor of of https://github.com/aws-quickstart/quickstart-mongodb-atlas.
