### ISSUE TITLE
Disable Transparent Huge Pages

### ISSUE THREAD

**Issue by alexraju91** [aws-quickstart/quickstart-mongodb#8]
Need to disable THP for best performance with MongoDB

https://docs.mongodb.com/manual/tutorial/transparent-huge-pages/

**Comment by vsnyc** [comment]
This will be fixed in the next release.
Commit:
https://github.com/vsnyc/quickstart-mongodb/commit/eac7e0c905e2913819569b9b4cbf1f496a3261f1
