### ISSUE TITLE
Repo / Quick Start Depreciation 

### ISSUE THREAD

**Issue by Zuhairahmed** [aws-quickstart/quickstart-mongodb#83]
@vsnyc can we depreciate this repo and associated Quick Start (https://aws.amazon.com/solutions/partners/mongodb/)? aligned with team and agree with your earlier suggestion, we would like to  go all in on MongoDB Atlas Quick Starts going forward. we can re-direct customers interested in this self-managed MongoDB repo which is no longer actively maintained to the MongoDB Atlas one which is actively being maintained.

**Comment by vsnyc** [comment]
We have removed the old Partner Solution page: https://aws.amazon.com/solutions/partners/mongodb/, and added a redirect to https://aws.amazon.com/solutions/partners/mongodb-atlas/. 

We will also archive this repository and add a note in the README to refer to the mongodb-atlas repo.

**Comment by Zuhairahmed** [comment]
perfect. thank you @vsnyc
